# Generated by Django 5.0.6 on 2025-02-22 17:21

from django.db import migrations

def add_colleges(apps, schema_editor):
    College = apps.get_model('core', 'College')
    colleges = [
        {'id': 1, 'name': 'COCIS'},
        {'id': 2, 'name': 'CEDAT'},
        {'id': 3, 'name': 'LAW'},
        {'id': 4, 'name': 'CAES'},
        {'id': 5, 'name': 'CHUSS'},
        {'id': 6, 'name': 'CONAS'},
        {'id': 7, 'name': 'EDUC'},
        {'id': 8, 'name': 'CHS'},
        {'id': 9, 'name': 'COVAB'},
        {'id': 10, 'name': 'COBAMS'}
    ]
    for college in colleges:
        College.objects.get_or_create(id=college['id'], defaults={'name': college['name']})

def remove_colleges(apps, schema_editor):
    College = apps.get_model('core', 'College')
    College.objects.filter(id__in=range(1, 11)).delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RunPython(add_colleges, remove_colleges),
    ]
